services:
  - type: web
    name: chatsafari-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://chatsa.netlify.app
    healthCheckPath: /health
    autoDeploy: true
